version: "3.7"

services:
  database-caramela:
    image: postgres
    container_name: database-caramela
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=caramela
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: caramela-api
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links: 
      - database-caramela
    depends_on: 
      - database-caramela

volumes:
  pgdata:
    driver: local